### ISSUE TITLE
URLs are unreachable

### ISSUE THREAD

**Issue by fardinkamal62** [Sayad-Uddin-Tahsin/BBC-News-API#2]
Hey man,

I wanted to use your API endpoint `https://bbc-api.tah3.repl.co/bengali/news` but it's giving me `404 page not found`.

**To Reproduce**
Go to any URL of `https://bbc-api.tah3.repl.co/<language>/<type>` and it'll give same behavior.

**Comment by Sayad-Uddin-Tahsin** [comment]
Hey @fardinkamal62,

I wanted to personally apologize for the inconvenience you experienced while trying to access our API endpoint at https://bbc-api.tah3.repl.co/bengali/news. I totally understand how frustrating it must have been to encounter a 404 page not found error. I'm really sorry about that.

But guess what? I've taken care of the issue, and now you should be able to access the desired URL without any problems. I apologize for the delay in getting things fixed and for any inconvenience it may have caused you.

By the way, I wanted to let you know that due to some recent changes in the structure of BBC websites, the image links for some news articles may not be available. So, when using the API, make sure to implement a proper condition to handle such cases effectively.

I also wanted to take a moment to personally thank you for using our API. Your support means a lot to me, and I genuinely appreciate it. If there's anything else I can assist you with or if you just want to chat, please feel free to reach out. I'm here to help!

Once again, I apologize for the inconvenience, and I truly appreciate your patience and understanding. Keep up the great work, and have a fantastic day!

Warm regards,
Tahsin

**Comment by fardinkamal62** [comment]
Thank you so much @Sayad-Uddin-Tahsin , it's working fine now
